# Generated by Django 4.1.5 on 2023-02-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_image_post_image_name_alter_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name=models.CharField(db_index=True, max_length=150)),
        ),
    ]
